### ISSUE TITLE
poco里面for循环的代码有个地方报错，修改了下就好了

### ISSUE THREAD

**Issue by Mzcom** [yeziyezi/airtest-arknights#1]
for star in poco("star"):改成for star in poco("playDragAndDrop").child("star"):

**Comment by yeziyezi** [comment]
请问这句代码是在哪里看到的，arknights.py中没有for循环啊😂

**Comment by Mzcom** [comment]
嘶！尴尬了，回复错了 你的代码没问题！看了你的airtest后又去瞅了眼poco发现有问题就顺便提交了 没想到是你的地址啊啊啊对不起！

**Comment by yeziyezi** [comment]
没事没事😂
